name: Keep Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Cada 5 minutos

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Send a keep-alive request
        run: |
          curl -sS https://019a6fc8-201b-421c-af04-56a47e118d8b-00-y9lb426rwlg1.picard.replit.dev
